# DO NOT EDIT THIS FILE!
#
# Python module CorbaServer__POA generated by omniidl

import omniORB
omniORB.updateModule("CorbaServer__POA")

# ** 1. Stub files contributing to this module
import server_command_corba_idl

# ** 2. Sub-modules

# ** 3. End
