# DO NOT EDIT THIS FILE!
#
# Python module CorbaServer generated by omniidl

import omniORB
omniORB.updateModule("CorbaServer")

# ** 1. Stub files contributing to this module
import server_command_corba_idl

# ** 2. Sub-modules

# ** 3. End
